name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    if: github.repository == 'hthienloc/gonhanh.org'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync branches
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git checkout dev
          git merge origin/main --no-edit
          git push origin dev
